language: julia
os:
  - linux
  - osx
julia:
  - 1.0
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
  fast_finish: true
notifications:
  email: false
after_success:
  - julia -e 'using Pkg; Pkg.add("Coverage")'
  - julia -e 'using Coverage; Codecov.submit(process_folder())'
before_install:
- openssl aes-256-cbc -K $encrypted_fbf94d2678c4_key -iv $encrypted_fbf94d2678c4_iv
  -in .cdsapirc.enc -out $HOME\/.cdsapirc -d
